global:
  scrape_interval: 10s  # How frequently to scrape the target

scrape_configs:
  - job_name: 'otel-collector-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
