server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_logs
          __path__: /logs/app.log

  - job_name: worker_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: worker_logs
          __path__: /logs/worker.log