basePath: /api
definitions:
  api.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api.ProfileResponse:
    properties:
      id:
        type: integer
      roles:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  api.RegisterAccountRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  api.RegisterAccountResponse:
    properties:
      message:
        type: string
    type: object
  helpers.GeneralResponse:
    properties:
      errors:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a starter go project
  title: gostarter api
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login an account
      parameters:
      - description: Login Details
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
      summary: Login an account
      tags:
      - Account
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout an account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
      summary: Logout an account
      tags:
      - Account
  /v1/auth/profile:
    get:
      consumes:
      - application/json
      description: Get account profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ProfileResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
      summary: Get account profile
      tags:
      - Account
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new account
      parameters:
      - description: Account to register
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/api.RegisterAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RegisterAccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.GeneralResponse'
      summary: Register a new account
      tags:
      - Account
swagger: "2.0"
