package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"gostarter/internals/delivery/http/graphql/generated"
	"gostarter/internals/domain"
	"gostarter/pkg/utils"
)

// GetAccountByID is the resolver for the getAccountById field.
func (r *queryResolver) GetAccountByID(ctx context.Context, id int) (*domain.Account, error) {
	return r.AccountService.GetAccountByID(ctx, id)
}

// GetAccountByEmail is the resolver for the getAccountByEmail field.
func (r *queryResolver) GetAccountByEmail(ctx context.Context, email string) (*domain.Account, error) {
	return r.AccountService.GetAccountByEmail(ctx, email)
}

// ListAccounts is the resolver for the listAccounts field.
func (r *queryResolver) ListAccounts(ctx context.Context, limit *int, offset *int) ([]*domain.Account, error) {
	p := utils.PaginationParams{
		Page: *offset,
		Size: *limit,
	}
	return r.AccountService.ListAccounts(ctx, p)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
